services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jc_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jc_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jc_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - jc_network

networks:
  jc_network:
    driver: bridge
